### ISSUE TITLE
Color for type is wrong depending on arg name

### ISSUE THREAD

**Issue by montanaflynn** [atom/language-go#126]
If an argument name ends with lowercase `type` the type will be a different color:

<img width="555" alt="screen shot 2017-05-22 at 4 12 09 pm" src="https://cloud.githubusercontent.com/assets/24260/26332108/83c808b6-3f09-11e7-86d1-028875d3ef03.png">

**Comment by joefitzgerald** [comment]
Nice find. Thanks for reporting!

**Comment by 50Wliu** [comment]
This was fixed by #117 in Atom 1.18.0, and there's a spec testing for it [here](https://github.com/atom/language-go/blob/c14edbe95481aec254180cf33b37cf697e8d7f60/spec/go-spec.coffee#L458-L461).

![no-more-lookbehinds](https://cloud.githubusercontent.com/assets/2766036/26338428/dea95c50-3f4d-11e7-8799-77dd93ac14ba.png)
