### ISSUE TITLE
type name not colored in block type statement

### ISSUE THREAD

**Issue by eternal-flame-AD** [atom/language-go#155]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The type name in block type statements is not colored the same as regular type declarations did.

### Steps to Reproduce

Sample code:
```golang
type (
	A struct {
		foo string
		bar int
	}
	B interface {
		baz()
	}
)

type C struct {
	foo string
	bar int
}

type D interface {
	baz()
}
```

**Expected behavior:** Type name "A" "B" "C" and "D" should have consistent colors.

**Actual behavior:** See the screenshot below, "A" and "B" are not colored correctly:
![image](https://user-images.githubusercontent.com/35571479/47056492-2b618380-d1ef-11e8-813a-d0a4f194d030.png)

**Reproduces how often:** Always.

### Versions

Atom    : 1.31.2
Electron: 2.0.11
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.3
npm  6.4.1
node 10.12.0 x64
atom 1.31.2
python 2.7.15
git 2.19.1

OS: Linux 4.18.14-arch1-1-ARCH

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report!

This is fixed if you use the new [Tree-sitter](http://tree-sitter.github.io/tree-sitter) parsing system, which is enabled by default in Atom 1.32 Beta. If you're not the beta channel, you can enable it manually by checking the `Use Tree-sitter Parsers` box in the settings view, or wait for Atom 1.32 Stable to be released.

Here's how it looks with Tree-sitter:

![image](https://github-slack.s3.amazonaws.com/monosnap/untitled__workflight-manual.atom.io_2018-10-16_22-52-41.png)

If you are interested in fixing this bug for the TextMate grammar system used in other projects (such as VSCode) we would be happy to accept a PR, however we probably won't prioritize work on these kinds of things ourselves, since Atom is moving away from TextMate for this language.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), I'm closing this issue as it no longer affects Atom.
