### ISSUE TITLE
Enhancement: Highlight *.gotpl files

### ISSUE THREAD

**Issue by mcandre** [atom/language-go#169]
`*.gotpl` is another common file extension for Go template files. Could we have this file extension added to the default Go template file pattern list?

**Comment by rsese** [comment]
Thanks @mcandre - we're currently trying to not make or accept this type of change since people can [customize how Atom recognizes files as specific languages](https://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-language-recognition) and we'd prefer that people use this customizability rather than making changes to the language packages.
