### ISSUE TITLE
In TextMate grammar, string in map declaration is incorrectly scoped

### ISSUE THREAD

**Issue by alexr00** [atom/language-go#170]
Given this go snippet:
````Go
package main

var test map[string]string = map [string]string{}
//                     ^this string
````
The value indicated in the snippet above is incorrectly scoped as `variable.other.assignement.go`.

**Comment by rsese** [comment]
Thanks for the report!  Looks like this isn't an issue with Tree-sitter (1.37.0-nightly22 on macOS 10.12.6):

![go-map](https://github-slack.s3.amazonaws.com/monosnap/untitled_2019-03-28_01-09-17.png)

So we'll go ahead and close, but let me know if I'm misunderstanding :v:

---

As you may have heard, we are migrating from our old [first-mate grammar engine](https://github.com/atom/first-mate) to the [new Tree-sitter engine](https://blog.github.com/2018-10-31-atoms-new-parsing-system/). This will enable a number of new features, more consistent syntax highlighting, and better performance, among other benefits. In order to free up our limited resources, we have decided to stop maintaining the first-mate grammar when there is a built-in Tree-sitter grammar available. Since this issue applies only to the first-mate grammar, we are going to close it. Please let us know if we have misunderstood the description of the problem.
