### ISSUE TITLE
Feature request: add scope to all types, not just builtins

### ISSUE THREAD

**Issue by joeshaw** [atom/language-go#172]
The various primitive types are assigned scopes, but custom types are not.  I'd like for all my types to have the same color in my VSCode theme.

![image](https://user-images.githubusercontent.com/39916/57156858-11634900-6dad-11e9-87cc-f1938d5b4c9f.png)

In the above screenshot, I would like for `io.Reader` and `*x509.Certificate` to be red like `error`.  Unfortunately, there are no scopes attached to it.

![image](https://user-images.githubusercontent.com/39916/57156904-3788e900-6dad-11e9-8514-23d0cb3827af.png)

I was thinking a generic scope like `storage-type` would be applied to it.

I originally filed this against vscode-go, https://github.com/Microsoft/vscode-go/issues/2491

**Comment by rsese** [comment]
Thanks for reaching out!

With Tree-sitter enabled it looks like both `reader` and `Certificate` are both `support.storage.type` e.g. for `reader`:

![go-types](https://user-images.githubusercontent.com/734194/57965112-2095db00-7905-11e9-8aa4-433295a5f173.png)

> I'd like for all my types to have the same color in my VSCode theme.

/cc @ramya-rao-a from https://github.com/microsoft/vscode-go/issues/2491 - as you may have heard, we are migrating from our old [first-mate grammar engine](https://github.com/atom/first-mate) to the [new Tree-sitter engine](https://blog.github.com/2018-10-31-atoms-new-parsing-system/). This will enable a number of new features, more consistent syntax highlighting, and better performance, among other benefits. In order to free up our limited resources, we have decided to stop maintaining the first-mate grammar when there is a built-in Tree-sitter grammar available. Since this issue applies only to the first-mate grammar, we are going to close it. Please let us know if we have misunderstood the description of the problem.

**Comment by joeshaw** [comment]
Thanks for the info. @rsese @ramya-rao-a Is the right next step for me to file a bug against microsoft/vscode-go to request switching to the new tree-sitter engine if there isn’t one already?

**Comment by ramya-rao-a** [comment]
In that case the next step would be to log an issue in the VS Code repo i.e. https://github.com/Microsoft/vscode because the grammar is being provided by VS Code itself and not the Go extension
