### ISSUE TITLE
Adding more common go package snippets

### ISSUE THREAD

**Issue by paulvollmer** [atom/language-go#177]
## Summary

Adding snippets for packages like `fmt`, `strings`, `io` etc.

## Motivation

If the `language-go` package include more snippets for common used language features like `string.Split` or `ioutil.ReadFile` the work by a developer can be speed up a lot.
Because currently there is only a small set of snippets at this package a lot of code a developer will write cannot be autocomplete.

I know it is a lot of work but if it's done, it will speed up a lot of atom user writing go code.

The question is how many snippets atom can handle without performance issues and which go package should be added.

I'm free to work on that task

**Comment by rsese** [comment]
Thanks for the suggestion!

We generally don't accept modifications for snippets in the language packages since they are easily overridden and we expect that people will do so for their own purposes. We provide instructions on how to create your own snippets in the [Flight Manual](https://flight-manual.atom.io/using-atom/sections/snippets/), and viewing a language package that provides snippets allows you and anyone else to copy the current version as a starting place for creating your own.

Thanks again for the suggestion but we're going to leave things as they are for now unless we're fixing a current snippet that produces invalid code.

**Comment by paulvollmer** [comment]
Thanks for the answer.

This is totally fine for me and i'll build my own golang snippets.
