### ISSUE TITLE
Highlighting for non-primitives

### ISSUE THREAD

**Issue by StabbyCutyou** [atom/language-go#48]
Hello,

I was trying to find a way to get non primitive types (either structs from the core libs, or structs from imported libraries / the current codebase) to get highlighted like primitives do, but can't really find where you define primitives in the grammars of language-go.

Am I barking up the wrong tree, and need to look at something deeper in Atom itself? or is this just currently not really a thing I should expect to be able to do?

Thanks

**Comment by svanharmelen** [comment]
@StabbyCutyou this is currently not possible with the language-go package. In order to support such a use case the syntax should be parsed using an ast tree instead of the current regexp based approach. But changing that will not be a straight forward (if at all possible) change to implement.

So I'll close this one for now, but will of course accept a PR implementing this if anyone is up for it :wink:
