### ISSUE TITLE
No more "item" placeholder with "forr" snippet

### ISSUE THREAD

**Issue by arthurwhite** [atom/language-go#60]
Hi,

The [a6a571c commit](https://github.com/atom/language-go/commit/a6a571cdaa0f1f74bb07eebb7df9030a2e9334e4#diff-4122efdf9c03b6cf5cde6fbf421f7c69R43) removed the `item` placeholder in the `forr` snippet.
It went from…
```CSON
'for range statement':
  'prefix': 'forr'
  'body': "for ${1:index}, ${2:item} := range ${3:list} {\n\t$0\n}"
```
…to…
```CSON
'for range statement':
  'prefix': 'forr'
  'body': "for ${1:var} := range ${2:var} {\n\t$0\n}"
```
It was faster to:
- replace `index` by `_` when using only the item.
- remove `, item` when using only the index.

Isn't this a regression?
The Go's range loop is used a lot to the get items only, without indexes:
```Go
for _, item := range list {
	// Only need item.
}
```

**Comment by svanharmelen** [comment]
@arthurwhite this was actually on purpose... The `for-range` loop can have many different forms and this seems to be the most generic approach making it easy to use whichever form you need.

Let's have a closer look at the options. There are 3 forms you can use:

```go
for i, v := range x {
	// note that i can be an index when ranging over a slice/array,
	// or a key when ranging over a map
}
```

```go
for i := range x {
	// again i can be an index or a key
}
```

```go
for range x {
	// here you don't have access to any value, just the iteration itself
}
```
As you can see you can have either zero, one or two items between the `for` and the `range` keywords. Of course I have to admit that using a `for-range` loop with zero items is not seen very often, but it is a valid use case.

So let's look at the keyboard actions needed for all these different options:

- 0: when you want no items at all you just press `del` at the first tab stop to remove the item
- 1: when you want one item, you just type the name you want to use at the first tab stop
- 2: when you want two items, you just type them both at the first tab stop (in one go, so `_, v`) before pressing tab again to move on to the next tab stop

IMO this requires the least amount of typing for all use cases. Even if you want to have 2 items, I doubt if it would actually be easier and/or require less typing when having 2 separate tab stops. You would have to type `_` press tab again and type `whatever`. So that's just about as much typing as `_, whatever`

Makes sense?

**Comment by arthurwhite** [comment]
It makes, yes.
So I just need a couple of days to adapt myself.

90% of the time, I use the range loop only for values.
Now as I see a singe placeholder, I directly type the variable name, almost forgetting there was a `_, ` before. And unlike many other languages, a single receiver takes the index/key and not the value… :bomb:

But thank you anyway!
