### ISSUE TITLE
Follow naming conventions

### ISSUE THREAD

**Issue by MaximSokolov** [atom/language-go#62]
According [TextMate naming conventions](http://manual.macromates.com/en/language_grammars#naming_conventions):
- [ ] `func` should be `storage.type.function` Now: `keyword`

Related issue is atom/atom#8430

**Comment by svanharmelen** [comment]
Working on it... Doing a little refactor that makes the whole package behave much closer to the TextMate conventions...

**Comment by svanharmelen** [comment]
I'm taking a little more time to fix this, as it turns out a lot more than only this scope name needed to be fixed to get this package to the next level. So I just finished with updating the scope names and refactoring a lot of the regexps and some tests.

It turned out some tests didn't test correct and everything not scoped as something specific was scoped as a variable :disappointed: The regexps needed to fix that were quite challenging (probably the reason why it wasn't done already), but there in and working perfectly :smiley:

I did however notice one last (IMO) use case around variables that currently didn't exist in the regexps and tests and that I want to add that one before creating a PR for all of this.

So it coming, but I will need to finish it after the weekend...
