### ISSUE TITLE
Inconsistent var/const highlighting

### ISSUE THREAD

**Issue by JormaSnow** [atom/language-go#77]
I am seeing very inconsistent highlighting of constants and variables depending on context. I updated the *language-go* package from version 0.39.0 to 0.41.0 and Atom from version 1.2.4 to 1.3.2, just to ensure that I was up-to-date but I still get the same inconsistencies.

I am using the *One Dark* theme for both UI and Syntax Themes. Linux Mint 17.1 KDE desktop. I have tested for these errors, with essentially the same results, using various themes.

Here is a summary of what I am seeing: 
* When I declare a const the name is red. `const fourtyTwo = 42 // "fourtyTwo" is red`  (that's usual)
* In something like `meaning := fourtyTwo` fourtyTwo is now gray.
* When I define a struct the field names are gray. `type user struct{ name string } // "name" is gray` (seems like they should also be red)
* When I make a custom type and I use a built-in type, the built-in type's name is highlighted purple. `type color uint8 // "uint8" is purple` (the usual color)
* When I make a custom type from a user defined type it is gray. `type hue color //"color" is gray` (maybe that's intentional... not a reserved word, so purple doesn't make sense and gold would look odd... I don't have a great suggestion here.)
* When I use the var key word the name of the variable is red. `var name string //"name" is red` (usual)
* When I do something with the same variable later it is gray. `len(name) // now "name" is gray`  (shouldn't it be red?)
* When I assign using := the left side var name is red; the right side gray. So in `bar := foo // "bar" red, "foo" gray` 

*Really* real examples:
```go
const (
    dbUser     = "user"
    dbPassword = "password"
    dbName     = "maintenance"
    dbHost     = "database.host"
)
```
In this context "dbUser", "dbPassword", "dbName" and "dbHost" are all highlighted red.

Later in the code:
```go
    dbinfo := fmt.Sprintf("postgres://%s:%s@%s/%s?sslmode=require",
		dbUser,
		dbPassword,
		dbName,
		dbHost,
	)
```
In this context "dbUser", "dbPassword", "dbName" and "dbHost" are each gray. 

The example `var db *sql.DB` and `db, err = sql.Open("postgres", dbinfo)` highlights the variables "db" and "err" in red, then later `defer db.Close()` has "db" in gray and "err" when checked, as in `if err != nil {...}` is gray.

In `item := r.PostFormValue("item")` "item" (left side) is red and "r" is gray. A few lines later "item", when used in the args for `db.Query()`, is gray.

Also in `item := r.PostFormValue("item")`  "PostFormValue" is blue but in `if r.Method == "POST" {...}` "Method" is in gray.

And another: `var i int` "i" is a red and a couple of lines later in `i++` the "i" is gray.

A couple of other odd ones: 

"string" as a type highlights green `var name string // "string" is green ` (the same color as string literals). All other built-in types seem to highlight purple.

Package names used to highlight, as in "http" from `http.ListenAndServe` and now are gray.

func/method parameters used to be red (as were the arguments passed in if I recall correctly) , now they are gray. They are at least consistent to each other, but they felt more comfortable to me when they matched the red pattern of variables.

**Comment by svanharmelen** [comment]
It would help if you could look at the scopes that are assigned to the different parts of the code examples. 

For example when looking at the scope of `dbHost` here:

```go
var (
    dbUser     = "user"
    dbPassword = "password"
    dbName     = "maintenance"
    dbHost     = "database.host"
)
```

it shows that it is assigned the scope `variable.other.assignment.go` which is correct. When you use `dbHost` at some later point in your code, it will just be assigned the scope `source.go`. This is because there is now way to tell what `dbHost` is in this context as the assigning of scopes is done based on regular expressions and not on the AST. So in this case it's currently the best we can do with the options we have to assign scopes.

So let's look at your findings:
- When I declare a const the name is red. const fourtyTwo = 42 // "fourtyTwo" is red (that's usual)
- In something like meaning := fourtyTwo fourtyTwo is now gray.
  - As explained above, this is as good as it gets when using regexps and not the actual AST
- When I define a struct the field names are gray. type user struct{ name string } // "name" is gray (seems like they should also be red)
  - This is correct behaviour, you define a field name not a variable
- When I make a custom type and I use a built-in type, the built-in type's name is highlighted purple. type color uint8 // "uint8" is purple (the usual color)
  - Again this is correct behaviour as far as I can tell. `uint8` is a build-in type and so is scoped as such
- When I make a custom type from a user defined type it is gray. type hue color //"color" is gray (maybe that's intentional... not a reserved word, so purple doesn't make sense and gold would look odd... I don't have a great suggestion here.)
  - Think by now you understand why it is like this
- When I use the var key word the name of the variable is red. var name string //"name" is red (usual)
- When I do something with the same variable later it is gray. len(name) // now "name" is gray (shouldn't it be red?)
-When I assign using := the left side var name is red; the right side gray. So in bar := foo // "bar" red, "foo" gray
  - Guess these are also explained by now right?

As for this example `Also in item := r.PostFormValue("item") "PostFormValue" is blue but in if r.Method == "POST" {...} "Method" is in gray.`, I believe this makes perfect sense. `r.PostFormValue()` is a function and `r.Method` is a variable, so they will be assigned different scopes.

**Comment by JormaSnow** [comment]
OK. That does make sense; sorry I didn't think through the subtleties or details in some of those examples. Thanks for taking the time to explain.

But what about:

> And another: var i int "i" is a red and a couple of lines later in i++ the "i" is gray.

I think you've explained the difficulty there but really they *should* match.

Wouldn't is just make more sense to leave the "i" in `var i int` without highlighting so that it matches the i in  `i++`.

Comparing apples to pears: in *Sublime Text* both "i"s in that example are white--I assume that's the un-highlighted color.

Also:

> "string" as a type highlights green var name string // "string" is green (the same color as string literals). 
> All other built-in types seem to highlight purple.

This does appear to be a legitimate mistake unless there is something else I am missing.

**Comment by svanharmelen** [comment]
> But what about:
> 
> > And another: var i int "i" is a red and a couple of lines later in i++ the "i" is gray.
> 
> I think you've explained the difficulty there but really they should match.

Yeah I think I agree.. This one is easy to find with a regexp, so we could/should add a fix for this one.

> Wouldn't is just make more sense to leave the "i" in var i int without highlighting so that it matches the i in i++.

Well, this package is all about trying to scope the syntax as good as possible. So we should scope everything we can with the appropriate scopes. Whether or not it should be highlighted and with what colours is up to the theme packages. If you for example use [this](https://atom.io/themes/monokai) theme you would get a very similar highlighting experience as you have with Sublime.

> Also:
>
> > "string" as a type highlights green var name string // "string" is green (the same color as string literals). 
> > All other built-in types seem to highlight purple.
>
> This does appear to be a legitimate mistake unless there is something else I am missing.

I think this has to do with your theme. Again you would need to look at the assigned scopes. If I check that here I see that `string` in `var s string` is scoped like `` which is perfectly fine of course. Again the [Monokai](https://atom.io/themes/monokai) theme highlights this just like you described, so that clearly shows it's a matter of how the theme package is build.

**Comment by JormaSnow** [comment]
OK. Thanks again. I never imagined syntax highlighting would be as complex as it is :)
