### ISSUE TITLE
Incorrect brackets matching

### ISSUE THREAD

**Issue by dyatlov** [atom/language-go#86]
guys are discussing the change: https://news.ycombinator.com/item?id=10993470

And found out this:

```go
someFunction( anotherFunction( "cool :)" ) )
```

Brackets matching becomes incorrect here.. same applies to PHP and other languages.. 

You should consider rewriting regexes to something more smart.

**Comment by svanharmelen** [comment]
@dyatlov unfortunately it is not up to the `language-go` package to move away from regexes. Currently Atom does not support any other approach so we're kind of stuck using regexes for the time being.

That said, there are some ongoing discussions about improving this within Atom by using syntax trees instead of regexes. This would of course be a very big improvement, but it will take some time before we get there...

As for this specific issue, I'll be more then happy to merge a PR fixing this one :wink:

**Comment by davisford** [comment]
Actually, no offense @dyatlov but that isn't valid `go`.  I do think there are other related issues filed under `atom/bracket-matcher`.

I just filed one over there that is somewhat specific to go, but maybe it belongs over here? https://github.com/atom/bracket-matcher/issues/209

**Comment by 50Wliu** [comment]
@davisford I think your issue should belong over here, as each grammar writes their own auto-indent rules.  bracket-matcher only handles bracket autocompletion and matching, not indentation.

As for @dyatlov's initial issue, that has already been reported at atom/bracket-matcher#23 and atom/bracket-matcher#78.

For the foreseeable future, grammars will remain regex-based.  A more advanced way of parsing grammars through I believe a syntax tree is being worked on, but is far from completion.
