### ISSUE TITLE
Colors in Go broken when multi dimensional arrays are declared

### ISSUE THREAD

**Issue by aeschli** [atom/language-go#98]
```go
var e [][]*aType       // ( bug in highligher?)
```

The double slash and everything after should be highlighted in green (comment), but is showing as white, but is working code.

_Copied from original issue: Microsoft/vscode-go#531_

**Comment by aeschli** [comment]
_From @ramya-rao-a on October 14, 2016 17:33_

Thanks for reporting this @sdwarwick! 
This is a bug. 
Single dimensional array declarations are fine as long as the array size is not defined. 

![image](https://cloud.githubusercontent.com/assets/16890566/19396740/60d058ee-91f9-11e6-9067-ba5e28371eb2.png)


Since the colorization for `.go` files is defined in VS Code itself at https://github.com/Microsoft/vscode/tree/master/extensions/go, will move this to VS Code repo

**Comment by cbcoutinho** [comment]
I ran into this bug the other day and wanted to post some additional peculiarities instead of starting a new issue.

Below is a screenshot of a simple go file. Line 15 is uncommented for illustration, but must be commented out to be valid go code.

As was stated before, variable array initialization is correct when no length is given, but not when there is a length. Even stranger, the line where the length in the initialization is a letter (line 15, also not valid go code, btw) is correctly highlighted.

![screenshot from 2017-02-06 04-23-08](https://cloud.githubusercontent.com/assets/12901868/22633743/848d9910-ec24-11e6-8ee9-fafebc41318e.png)

I think it's an issue in the regex in the 'variables' section ([lines 470-539](https://github.com/atom/language-go/blob/master/grammars/go.cson#L470-L539)), but I'm no expert in regex and I couldn't determine what the issue could be.

Just to quench my own curiosity, I'm also curious how atom grammars work. From what I could determine, the bug in question is related to lines that begin with `var`, or [Single line variable declarations](https://github.com/atom/language-go/blob/master/grammars/go.cson#L212-L222), reproduced below. I guess this means that 'var' is group 0 and isn't captured, and then everything after var and some whitespace is captured in group 1:
```
{
  'comment': 'Single line variable declarations/assignments'
  'match': '(?<=var)\\s+(.*)$'
  'captures':
    '1':
      'patterns': [
        {
          'include': '#variables'
        }
      ]
}
```

After that it sends the remainder to #variables, but I don't understand how that part works. In `variables`, there are 3 different patterns. Does it just check one after another to see if one sticks? I also don't see how the brackets could be handled in any of those patterns.  I thought it could be in the delimiters part, but that's only for commas, periods, and colons.

**Comment by 50Wliu** [comment]
I've been working on overhauling the variable matching.  This reminds me to get back to work on that :).

**Comment by 50Wliu** [comment]
Hey there @cbcoutinho, a few questions for you.  Can there be array _assignments_ (eg `var a []int = something`)?  Or can there only be array declarations?

**Comment by cbcoutinho** [comment]
I'm nowhere close to being an expert in go, so I'm not confident in
answering your question. From the few tutorials I have followed I would say
it's possible, and by that I mean it compiles - but I'm not sure if it's
valid code.

Cheers,
Chris
